# Generated by Django 4.2.5 on 2023-09-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=250)),
                ('edition', models.CharField(max_length=250)),
                ('origin', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('story_body', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
