# Generated by Django 4.2.5 on 2023-09-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='chapter',
            field=models.CharField(default='Chapter 1', max_length=250),
        ),
        migrations.AddField(
            model_name='story',
            name='story_title',
            field=models.CharField(default='Malik', max_length=250),
        ),
    ]
